# Generated by Django 5.2.11 on 2026-03-03 05:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_review_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='watchlist_movies', to=settings.AUTH_USER_MODEL),
        ),
    ]
