# Generated by Django 5.2.11 on 2026-03-03 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_movie_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='where_to_watch',
            field=models.CharField(blank=True, help_text='เช่น Netflix, Disney+, HBO GO', max_length=200, null=True),
        ),
    ]
